package com.opex.backend.user.dto;

import com.opex.backend.user.model.User;

import java.time.LocalDate;
import java.time.OffsetDateTime;

public record UserResponse(
        String id,
        String email,
        Boolean emailVerified,
        OffsetDateTime registrationDate,
        OffsetDateTime verificationEmailLastSentAt,
        String firstName,
        String lastName,
        String displayName,
        String identityProvider,
        String customerId,
        LocalDate dob,
        String country,
        String residence,
        String occupation,
        String preferredSecondFactor,
        Boolean secondFactorEnrollmentDeferred,
        String secondFactorMethod,
        OffsetDateTime secondFactorConfiguredAt,
        String vatFrequency,
        Boolean gdprAccepted,
        String legalVersion,
        String privacyPolicyVersion,
        OffsetDateTime privacyAcceptedAt,
        String termsOfServiceVersion,
        OffsetDateTime termsAcceptedAt,
        String cookiePolicyVersion,
        OffsetDateTime cookiePolicyAcknowledgedAt,
        Boolean strictlyNecessaryCookiesAcknowledged,
        String openBankingNoticeVersion,
        OffsetDateTime openBankingNoticeAcceptedAt,
        String openBankingConsentScopes,
        String fiscalResidence,
        String taxRegime,
        String activityType,
        Boolean vatExempt,
        Boolean startup,
        Boolean selfEmployed,
        Boolean mainActivity,
        Boolean publicHealthInsurance,
        String profilePicture,
        Double notificationBalanceThreshold,
        Boolean notifyCriticalBalance,
        Boolean notifySignificantIncome,
        Boolean notifyAbnormalOutflow,
        Boolean notifyConsentExpiration,
        Boolean notifySyncErrors,
        Boolean notifyQuarterlyVat,
        Boolean notifyMonthlyAnalysis,
        String answer1,
        String answer2,
        String answer3,
        String answer4,
        String answer5,
        Boolean isActiveSaltedge,
        Boolean isActive
) {

    public static UserResponse from(User user) {
        return new UserResponse(
                user.getId(),
                user.getEmail(),
                user.getEmailVerified(),
                user.getRegistrationDate(),
                user.getVerificationEmailLastSentAt(),
                user.getFirstName(),
                user.getLastName(),
                user.getDisplayName(),
                user.getIdentityProvider(),
                user.getCustomerId(),
                user.getDob(),
                user.getCountry(),
                user.getResidence(),
                user.getOccupation(),
                user.getPreferredSecondFactor(),
                user.getSecondFactorEnrollmentDeferred(),
                user.getSecondFactorMethod(),
                user.getSecondFactorConfiguredAt(),
                user.getVatFrequency(),
                user.getGdprAccepted(),
                user.getLegalVersion(),
                user.getPrivacyPolicyVersion(),
                user.getPrivacyAcceptedAt(),
                user.getTermsOfServiceVersion(),
                user.getTermsAcceptedAt(),
                user.getCookiePolicyVersion(),
                user.getCookiePolicyAcknowledgedAt(),
                user.getStrictlyNecessaryCookiesAcknowledged(),
                user.getOpenBankingNoticeVersion(),
                user.getOpenBankingNoticeAcceptedAt(),
                user.getOpenBankingConsentScopes(),
                user.getFiscalResidence(),
                user.getTaxRegime(),
                user.getActivityType(),
                user.getVatExempt(),
                user.getStartup(),
                user.getSelfEmployed(),
                user.getMainActivity(),
                user.getPublicHealthInsurance(),
                user.getProfilePicture(),
                user.getNotificationBalanceThreshold(),
                user.getNotifyCriticalBalance(),
                user.getNotifySignificantIncome(),
                user.getNotifyAbnormalOutflow(),
                user.getNotifyConsentExpiration(),
                user.getNotifySyncErrors(),
                user.getNotifyQuarterlyVat(),
                user.getNotifyMonthlyAnalysis(),
                user.getAnswer1(),
                user.getAnswer2(),
                user.getAnswer3(),
                user.getAnswer4(),
                user.getAnswer5(),
                user.getIsActiveSaltedge(),
                user.getIsActive()
        );
    }
}
