server.port=8082

spring.application.name=saltedgeproxy

spring.datasource.url=jdbc:postgresql://localhost:5433/opexdb
spring.datasource.username=opex
spring.datasource.password=Qm4p8Vn2zA7Lh3Rk9cT5xY
spring.datasource.driverClassName=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update

saltedge.app-id=${SALTEDGE_APP_ID:W9mkzmfEeInVWcsmsuP9H_a9IEZvgNN8mMqgammR4NU}
saltedge.secret=${SALTEDGE_SECRET:_8Y6VPSwvZ9LDejQ-M5nXJfoQl0UBCgxEgmNapcu1pE}
gdpr.policy.current-version=2026-03-12
