server.port=8082

spring.application.name=saltedgeproxy

spring.datasource.url=${APP_PG_JDBC_URL:jdbc:postgresql://${APP_PG_HOST:localhost}:${APP_PG_PORT:5433}/${APP_PG_DB:opexdb}}
spring.datasource.username=${APP_PG_USER:opex}
spring.datasource.password=${APP_PG_PASSWORD:opex}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update

saltedge.app-id=${SALTEDGE_APP_ID:W9mkzmfEeInVWcsmsuP9H_a9IEZvgNN8mMqgammR4NU}
saltedge.secret=${SALTEDGE_SECRET:_8Y6VPSwvZ9LDejQ-M5nXJfoQl0UBCgxEgmNapcu1pE}
saltedge.return-to-url=${SALTEDGE_RETURN_TO_URL:http://localhost:3000/success}
gdpr.policy.current-version=${LEGAL_OPEN_BANKING_VERSION:2026-04-09}
