server.port=8080

spring.application.name=backend
  
  # --- CONFIGURAZIONE DATABASE ---
spring.datasource.url=jdbc:postgresql://localhost:5433/opexdb
spring.datasource.username=opex
spring.datasource.password=Qm4p8Vn2zA7Lh3Rk9cT5xY
spring.datasource.driver-class-name=org.postgresql.Driver
  
  # --- CONFIGURAZIONE JPA/HIBERNATE ---
  # Crea/aggiorna le tabelle in automatico (ottimo per lo sviluppo, in prod si usa 'validate')
spring.jpa.hibernate.ddl-auto=update
  # Mostra le query in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
  
  # --- CONFIGURAZIONE SICUREZZA (RESOURCE SERVER) ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/opex
  
  # --- CONFIGURAZIONE KEYCLOAK ADMIN CLIENT ---
keycloak-admin.server-url=http://localhost:8081
keycloak-admin.realm=master
keycloak-admin.client-id=admin-cli
keycloak-admin.username=admin
keycloak-admin.password=kJWQ9TC4FKUFVNi9p2zw
keycloak-admin.target-realm=opex
  
  # --- CONFIGURAZIONE MICROSERVIZI ESTERNI ---
external-services.saltedge-microservice.url=http://localhost:8082

# --- CONFIGURAZIONE AWS S3 ---
aws.s3.bucket-name=opex-files
aws.s3.region=eu-central-1
aws.s3.access-key=test
aws.s3.secret-key=test