export interface UserProfile {
  name: string;
  displayName?: string | null;
  identityProvider?: string | null;
  email: string;
  emailVerified?: boolean;
  registrationDate?: string | null;
  residence: string;
  vatFrequency: string;
  logo: string | null;
  gdprAccepted: boolean;
  fiscalResidence?: string | null;
  taxRegime?: string | null;
  activityType?: string | null;
  firstName?: string;
  lastName?: string;
  country?: string | null;
  occupation?: string | null;
  preferredSecondFactor?: string | null;
  secondFactorEnrollmentDeferred?: boolean;
  secondFactorMethod?: string | null;
  secondFactorConfiguredAt?: string | null;
  customerId?: string | null;
  connectionId?: string | null;
  dob?: string | null;
  answer1?: string | null;
  answer2?: string | null;
  answer3?: string | null;
  answer4?: string | null;
  answer5?: string | null;
  privacyPolicyVersion?: string | null;
  privacyAcceptedAt?: string | null;
  termsOfServiceVersion?: string | null;
  termsAcceptedAt?: string | null;
  cookiePolicyVersion?: string | null;
  cookiePolicyAcknowledgedAt?: string | null;
  legalVersion?: string | null;
  strictlyNecessaryCookiesAcknowledged?: boolean;
  openBankingNoticeVersion?: string | null;
  openBankingNoticeAcceptedAt?: string | null;
  openBankingConsentScopes?: string[];
  notificationBalanceThreshold?: number;
  notifyCriticalBalance?: boolean;
  notifySignificantIncome?: boolean;
  notifyAbnormalOutflow?: boolean;
  notifyConsentExpiration?: boolean;
  notifySyncErrors?: boolean;
  notifyQuarterlyVat?: boolean;
  notifyMonthlyAnalysis?: boolean;
}
